### ISSUE TITLE
Security issue: allowFetch is insecure, using it with untrusted code is a security vulnerability 

### ISSUE THREAD

**Issue by justjake** [sebastianwessel/quickjs#1]
This library exposes the ability for the guest (untrusted) code to `fetch` with the same cookies as the host `fetch` function. You must not run untrusted code if enabling `fetch`. Library should come with a big blinking warning about what is safe and unsafe to enable when running untrusted code. It’s not a “sandbox” if the sandboxed code can call arbitrary HTTP APIs authenticated as the host context!

I recommend designing the allowFetch API to require an allow-list of URL prefixes, disable following redirects to URLs not in the allow list, and force a default rate-limit on the guest. 

Exposing fetch to untrusted code would be one of these vulnerabilities:

- server-side: https://owasp.org/Top10/A10_2021-Server-Side_Request_Forgery_%28SSRF%29/
- client-side CSRF: https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html#dealing-with-client-side-csrf-attacks-important

**Comment by sebastianwessel** [comment]
Yes, that is valid and the reason why it is disabled by default.
Currently, fetch is support is on a "technically" possible level.

My plan is, to abstract the fetch lib a bit more in the direction of module/plugin.
The allow-list is a good idea for a lot of use cases, but won't fit for any cases, where you do not know the URLs upfront.

The abstract idea is, to have the option, to provide the fetch functionality similar to console, and to only provide some basic adapter as default. The default one will stay basic and unrestricted to cover each use case.

This way, it can be adapted and aligned for specific needs, while keeping this lib focused on the core functionallity.

**Comment by sebastianwessel** [comment]
created as small proposal #3

**Comment by sebastianwessel** [comment]
fetch has been refactored and a bunch of options and security settings are available now. The functionality itself is a configurable adapter, which can be replaced by custom adapter

[https://sebastianwessel.github.io/quickjs/fetch.html](https://sebastianwessel.github.io/quickjs/fetch.html)
