### ISSUE TITLE
Being able to expose objects to the execution environment would be amazing!

### ISSUE THREAD

**Issue by mehmetron** [sebastianwessel/quickjs#33]
Thanks for the awesome library! I got it working within just a few minutes!

**Is your feature request related to a problem? Please describe.**
It's just a feature request. I want to expose an object with data and methods to the execution environment.

**Describe the solution you'd like**
Be able to expose large JS object to execution environment.

**Describe alternatives you've considered**
I don't know any other alternatives.

**Comment by sebastianwessel** [comment]
Hey @mehmetron ,

have you seen [Data Exchange Between Host and Guest](https://sebastianwessel.github.io/quickjs/basic.html)?
The best way to provide objects and functions is, to pass it into `env` in the configuration. This is not restricted to simple environment variable strings.

**Comment by mehmetron** [comment]
Ok, that makes sense. Thanks!

I was able to get the simple.html example working locally: https://github.com/sebastianwessel/quickjs/blob/main/example/browser/simple.html

But I couldn't get the app working in a reactjs app on codesandbox. It seems I'm being asked to import something from the nodejs standard library.

https://codesandbox.io/p/sandbox/vigilant-rubin-h4lp7q

**Comment by sebastianwessel** [comment]
I will have a look into the browser related stuff. I was mostly focusing on "runs in backend", because it is my personal use case, and the reason why I started this.
But seems, there are a lot of people, which have the "run in browser" use case scenario.

**Comment by mehmetron** [comment]
Yeah, running in the browser is probably a very big use case scenario.

For running on the backend, couldn't you just execute all the code in sandboxed docker containers and use something like gvisor to make it extra secure. You could even give the code access to a port using port forwarding. 

I think that's what replit does. They create a docker container, do port forwarding for two ports into the container, one port is for their program in the container so they can create/update/delete files/dirs in the container and do any other sort of operations, the other port is the one exposed to the user's program so the user can expose whatever they want to the internet.

**Comment by sebastianwessel** [comment]
@mehmetron thanks.
Running docker is for sure a valid option, but does not fit on many use cases.
As a real world example:
Imagine you have some edge IoT device (like raspberry), and there is some application running, which collects sensor data. The end-user can configure data pipelines and transformations with JavaScript functions, but should not be able to "hack" the whole system. Here, it is too slow, and it requires too many resources, to spin up individual docker containers, for each data pipeline.
Another example is, the usage in AI large language models with function calling. When you want to give the AI the possibility to generate and run small code very quickly.
