### ISSUE TITLE
chore: Remove QuickJS-emscripten-sync dependency

### ISSUE THREAD

**Issue by sebastianwessel** [sebastianwessel/quickjs#34]
Refactor data exchange between host and guest system to use standard quickjs-emscripten.

Reasons:

- reduce dependencies
- package seems not to be highly maintained

**Comment by digipigeon** [comment]
quickjs-emscripten-sync provides a lot of useful functionality in marshaling data, it would be a considerable amount of work to replace this functionality, in which my personal thoughts are that this time could be better spent.

Alternatively, the author of quickjs has mentioned "Consider integrating [quickjs-emscripten-sync](https://github.com/reearth/quickjs-emscripten-sync) for automatic translation." about integrating this directly into the quickjs-emscripten project. Maybe a discussion could be opened up to make this part of the quickjs-emscripten project with a strategic PR?

Just my thoughts, I hope you don't mind them. The project looks very interesting and I shall try to give it some testing soon.

**Comment by sebastianwessel** [comment]
There are several reasons to remove the quickjs-emscripten-sync.

In addition to the already mentioned things, there are also general, conceptual reasons.
The sync library tries to remove the barrier between host and guest, which results in some kind mix up.

As an example - let's imagine there is a class A in the sandbox like this:

```js
class A {
  methodB() {
     return 'hello'
  }
}
```

And an instance of this class is given to the host, quickjs-emscripten-sync creates an object on the host, which looks something like this:

```js
{
  methodB() {
     return sandboxContext.callFunction(classInstanceSandboxFunction)
  }
}
```
There is no clean (de-)serialization. And as soon as the sandbox instance is gone, these things can't be used anymore.
The intention is, to have a clean serialization between host and sandbox - similar to JSON encode/decode, which creates fresh instances.

Btw.: Thanks to the awesome work done in quickjs-emscripten(-sync), it isn't too much work. I've already done it - only some cleanup, tests and so on are missing.
