### ISSUE TITLE
Limit memory and CPU usage

### ISSUE THREAD

**Issue by danioso** [sebastianwessel/quickjs#35]
There is a problem with excessive memory consumption by a running script. Is there a way to set a limit on the amount of memory the runtime can use? same question for the CPU.  Otherwise, I think it will eventually consume all the memory, potentially crashing the entire service running this runtime.

```js
let memory = [];
while (true) {
    memory.push(new Array(1e6).fill('memory leak'));
}
```

**Comment by sebastianwessel** [comment]
Hi @danioso 
Yes, you can set memory limits for the general runtime via

```typescript

import { quickJS } from '@sebastianwessel/quickjs'
const { createRuntime } = await quickJS()
const { evalCode, vm } = await createRuntime()

const runtime = vm.context.runtime

runtime.setMemoryLimit(1024 * 640)
// Limit stack size
runtime.setMaxStackSize(1024 * 320)
```

Tbh: I didn’t tried it out yet. It’s coming from underlying [quickjs-emscripten lib](https://Gitgithub.com/justjake/quickjs-emscripten)

CPU restrictions can not simply set. Correct me if I’m wrong, but you can’t do it in Node.js in general. Must be done one layer down in the infrastructure - not on application level. Please have a look at [Basic Understanding](https://sebastianwessel.github.io/quickjs/basic.html) in the documentation, to find some advices to protect the host system.
