### ISSUE TITLE
REPL possibility?

### ISSUE THREAD

**Issue by MarketingPip** [sebastianwessel/quickjs#39]
Would there be any way we could create a REPL environment by storing / parsing global set variables etc?

(as well is there a way to set process.argv as global?)

**Comment by sebastianwessel** [comment]
If you set `env.MY_ENV_VAR`, it will be automatically set to `process.env.MY_ENV_VAR`.
`MY_ENV_VAR` can be a string or number, or function or object...

```ts
const { evalCode } = await createRuntime({
  allowFetch: true, // inject fetch and allow the code to fetch data
  allowFs: true, // mount a virtual file system and provide node:fs module
  env: {
    MY_ENV_VAR: 'env var value'
  },
})
```

Within any program, you can also do `globalThis.ANY_VAR = 'ANYTHING'` 

REPL will not simply possible, because of the nature of how things work with wasm & quickjs.
If the custom code is executed in the sandbox, the host system is basically blocked, until the code execution is completed.
To have some kind of REPL, you will need to rebuild the behavior of the event loop. QuickJS itself does not have an event loop like in node.js.

In general, I wonder, if QuickJS is the right choice for you at all - maybe something like [wasmer](https://github.com/wasmerio/winterjs) fits better for your needs?

**Comment by MarketingPip** [comment]
@sebastianwessel - I was curious if possibly use of babel could be applied here if option for stdin could be used. 

And I think this project is exactly what I need - just wondering how far it can be pushed. (If that makes sense)....

10 years ago this whole project wouldn't have been possible but look at things now ;)

**Comment by MarketingPip** [comment]
@sebastianwessel - as for repl inquiry too. Just as "fetch" can be injected etc as adapter. If we could inject other things into context as said outside function. Could we not block execution that way etc...? Either call function / return string or throw error if not string or function...?

**Comment by MarketingPip** [comment]
@sebastianwessel - to do this we need a way to tell if QuickJSUseAfterFree / or waiting for dispose... To avoid lifetime messages etc...

Example of how we could do this (tho need a flag to wait for next run - not implemented):

```js
let evalCode;
const nodeJS = async (code, outputCallback, errorCallback, processArgs=[]) => {
 

  const fetchAdapter = async (url, param) => {
  const res = await fetch(url, { ...param, mode: "cors" });
  return {
    status: res.status,
    ok: res.ok,
    statusText: res.statusText,
    json: async () => await res.json(),
    text: async () => await res.text(),
    formData: () => res.formData(),
    headers: res.headers,
    type: res.type,
    url: res.url,
    blob: async () => await res.blob(),
    bodyUsed: res.bodyUsed,
    redirected: res.redirected,
    body: res.body,
    arrayBuffer: async () => await res.arrayBuffer(),
    clone: () => res.clone(),
  };
};
  
   const quickJS = (await import("https://esm.sh/@sebastianwessel/quickjs@1.3.0")).quickJS
await import("https://esm.sh/typescript")
await import("https://esm.sh/@hazae41/symbol-dispose-polyfill");
  ///console.log(quickJS)
  const { createRuntime } = await quickJS('https://esm.sh/@jitl/quickjs-wasmfile-release-sync');
  
  
   if(!evalCode){
   evalCode = await createRuntime({
    allowFetch: false,
    allowFs: false,
    transformTypescript: true,
    fetchAdapter,
    env: {
      MY_ENV_VAR: 'env var value',
    },
    console: {
      log: (...message) => outputCallback(message),
      info: (...message) => outputCallback(message),
      warn: (...message) => outputCallback(message),
      error: (...message) => outputCallback(message),
    }
  });
   }
  

  try {
    const res = await evalCode.evalCode(code);
    console.log(res)
      //console.log(nodefs)
    return  res
  } catch (e) {
     
  }
};

const delay = (ms) => new Promise(resolve => setTimeout(resolve, ms));
const evalInRuntime = async (code) => {
  try {
    const res = await nodeJS(code);
 
    return res;
  } catch (e) {
    console.error(e.message);
  }
};

// Example REPL usage:
(async () => {
 //await initializeRuntime();
//
  let res =  await evalInRuntime(`let val = 10;`);
 

  res =  await evalInRuntime("val += 20;");
   

  res =  await evalInRuntime("return val");
  console.log("Result:", res);
})();
  
```

**Comment by sebastianwessel** [comment]
Even if it is wip, you can try this with this branch:
https://github.com/sebastianwessel/quickjs/pull/32

see example/basic for usage

**Comment by MarketingPip** [comment]
@sebastianwessel - is this example of how I did this any use to you?

![image](https://github.com/user-attachments/assets/5ec09c78-7adf-4b9b-a2cc-4ee4ea063875)


^ running all in the browser. Using a stdin - via my Termino.js library... Multi turn steps etc.. Using old / current version of library.
