### ISSUE TITLE
[Feature Request]: Add options to add to FS when using writeFile etc..

### ISSUE THREAD

**Issue by MarketingPip** [sebastianwessel/quickjs#44]
It would be great if we can access / update the provided vfs json object when files are wrote so we can get new content / files created within the runtime etc...

Possibly a flag or function to get updated vfs / memory etc... 

This possible relates to #39

**Comment by sebastianwessel** [comment]
Pls see the branch for the upcoming release:

https://github.com/sebastianwessel/quickjs/tree/28-feat-add-multiturn-support

Here, you should be able to access the virtual file system before and after each execution of custom scripts
