### ISSUE TITLE
[Issue]: readFile is splitting files in VFS src

### ISSUE THREAD

**Issue by MarketingPip** [sebastianwessel/quickjs#45]
When readFile is calling a file inside "src" like 

```json
{
   "src": {
       "textFile.txt": "Hello from the text file!",
   }
}
```

```js

import { readFileSync, readFile, writeFileSync } from 'node:fs'
async function run(){
readFile('./textFile.txt', 'utf8', (err, data) => {
  if (err) throw err;
  console.log(data);
});

console.log(readFileSync('./textFile.txt'))
}
await run()
```

we get:

```
Hello;
from;
the;
text;
file;
Hello;
from;
the;
text;
file;
```

When not in src like:

```json
{
   "src": {},
   "textFile.txt": "Hello from the text file!",
}
```

We get:

```
Hello from the text file!
Hello from the text file!
```

**Comment by sebastianwessel** [comment]
What exactly is the issue?

This one is event/stream based, where you get only partial parts, which are printed out to the console log. Each partial data is printed out as a new line.
```js
readFile('./textFile.txt', 'utf8', (err, data) => {
  if (err) throw err;
  console.log(data);
});
```
This prints:
> Hello
> from
> the
> text
> file!

The other `console.log(readFileSync('./textFile.txt'))` will read the whole file content and as it is sync, it will block until the whole file content is read and printed out.
This prints:
> Hello from the text file!

**Comment by MarketingPip** [comment]
@sebastianwessel - my bad. It seems I have documented this issue in correctly.  See below (and revised above)....

When using like this:

```json
{
   "src": {
       "textFile.txt": "Hello from the text file!",
   }
}
```

```js

import { readFileSync, readFile, writeFileSync } from 'node:fs'
async function run(){
readFile('./textFile.txt', 'utf8', (err, data) => {
  if (err) throw err;
  console.log(data);
});

console.log(readFileSync('./textFile.txt'))
}
await run()
```


we get:

```
Hello;
from;
the;
text;
file;
Hello;
from;
the;
text;
file;
```

**Comment by sebastianwessel** [comment]
Your code must be at least look like the code below, as `readFile` is event based.
The code execution will continue after call `readFile`, while calling the callback.

```ts
import { readFileSync, readFile, writeFileSync } from 'node:fs'
async function run(){

await new Promise((resolve)=>{
  readFile('./textFile.txt', 'utf8', (err, data) => {
    if (err) throw err;
    console.log('1', data);
    resolve()
  });
})


console.log('2',readFileSync('./textFile.txt'))
}
await run()
```

The output without the Promise is

```bash
2 Hello from the text file!
1 Hello from the text file!
```

I tried it on the current working branch, I there are no new lines at all.

**Comment by MarketingPip** [comment]
@sebastianwessel - just digging into this on my end. This seems to be an issue with MY code and not the library. 

TDLR; 
My output handler wasn't properly formatting things.
