### ISSUE TITLE
Test Runner / Mocha Not Working In Browser.

### ISSUE THREAD

**Issue by MarketingPip** [sebastianwessel/quickjs#50]
Issue when using Mocha ie: `import 'testRunner'`

It will return - 
```
[esm.sh] "node:fs" is not supported in browser environment.
```

As well - whenever you import this module name "testRunner". It automatically looks for test runner. 

Which from my understanding in documentation this should not be needed as this flag says other wise [here](https://github.com/sebastianwessel/quickjs/blob/9aa60d8a9230d5c21aa51ea2b061ad274fffe541/src/types/RuntimeOptions.ts#L38) - as it says usage is global for mocha / chai (meaning no import required for testRunner - since they both do the same thing it looks like).

**Comment by sebastianwessel** [comment]
Not sure where this `esm.sh` stuff is coming from as QuickJS is not using esm.sh

The package is `test` and not `testRunner`. I fixed the docs.

Example:

```ts
import { quickJS } from "../../src/index.js";

// General setup like loading and init of the QuickJS wasm
// It is a ressource intensive job and should be done only once if possible
const { createRuntime } = await quickJS();

// Create a runtime instance each time a js code should be executed
const { evalCode } = await createRuntime({
  allowFetch: true, // inject fetch and allow the code to fetch data
  allowFs: true, // mount a virtual file system and provide node:fs module
  env: {
    MY_ENV_VAR: "env var value",
  },
  enableTestUtils: true,
});

const result = await evalCode(`
  //import 'test'

  describe('mocha', ()=> {
    it('should work',()=>{
     expect(true).to.be.true
    })
  })

  const testResult = await runTests();

  export default testResult
`);

console.log(result); // { ok: true, data: '<!doctype html>\n<html>\n[....]</html>\n' }
```

You can enable the test runner (package test) via config or use it with import

**Comment by MarketingPip** [comment]
@sebastianwessel - that is very weird .-. lol 

I tried searching the repo and just was thinking GH search bar tool was sucking but - I have no clue WHY or WHERE my requests were getting uploaded. (I'll look in my code here again and report if I find any stupidity on my part)

**Comment by MarketingPip** [comment]
@sebastianwessel - so it appears this is coming from usage of CDN for ```quickjs-wasmfile-release-sync```. Not sure if there is away we can avoid this issue (I will try thinking of some solutions).

**Comment by MarketingPip** [comment]
![image](https://github.com/user-attachments/assets/7ad0f409-cdd4-4fe7-8fdd-170b3bc1dc93)

Just showing you too - tho there is some issue but Jest working in it...
