### ISSUE TITLE
Improve custom virtual file system and modue loader to allow relative imports

### ISSUE THREAD

**Issue by sebastianwessel** [sebastianwessel/quickjs#8]
Allow relative imports of source files from virtual file system.
Add documentation for virtual file system usage.

**Comment by MarketingPip** [comment]
@sebastianwessel - sorry to be a bothersome. Can I get an example of how to use this with a exported function as import in the vfs? 

ps; when using this via cdn in browser from esm.sh I am getting this error:
```
Uncaught TypeError: Failed to resolve module specifier '@jitl/quickjs-ng-wasmfile-release-sync'
```

**Comment by sebastianwessel** [comment]
Hey @MarketingPip,

Thanks for your interest in this library! I'm happy to help out if I can.

Are you looking to add a file to the virtual file system and then import it into your script? If so, you might find this example useful:

[Custom Module Example](https://github.com/sebastianwessel/quickjs/tree/main/example/custom-module)

Feel free to reach out if you have any more questions!

**Comment by sebastianwessel** [comment]
...regarding the usage in browser.

It is currently not the highest priority, but I will add some more documentation about it and I also need to investigate a bit more

Issue will be tracked here: #22

**Comment by MarketingPip** [comment]
@sebastianwessel - you're the best! Was right in front of my eyes! 

That said would be VERY cool to see this for usage of browser. (Would be very useful for in browser code editors 😉).

**Comment by sebastianwessel** [comment]
@MarketingPip 

Small doc: https://sebastianwessel.github.io/quickjs/usage-in-browser-and-providers.html

browser example: https://github.com/sebastianwessel/quickjs/tree/main/example/browser

Little test: https://sebastianwessel.github.io/quickjs/example.html (chrome only atm)

**Comment by MarketingPip** [comment]
@sebastianwessel - I see your CSS skills are way better than mine lol!

I got this when running
```js
caught TypeError: Symbol.dispose is not defined.
    at pt (quickJS.js:10:40)
    at evalCode (quickJS.js:148:43)
```

**Comment by sebastianwessel** [comment]
>  I see your CSS skills are way better than mine lol!
🤫 ChatGPT 

Which browser do you use? I've seen this too in Firefox & Safari - but not in Chrome for 🤷‍♂️ reason.

**Comment by MarketingPip** [comment]
@sebastianwessel older version of chrome running in indigo version.

**Comment by MarketingPip** [comment]
@sebastianwessel - I found a polyfill that solved this, maybe you want to document it or look into the polyfill itself further etc... 

See [here](https://github.com/hazae41/symbol-dispose-polyfill)

**Comment by MarketingPip** [comment]
@sebastianwessel - no chance you got to look at that poly fill?  (Possibly dynamically import it etc if not found...?) - Worked on my device to solve my issue.

**Comment by sebastianwessel** [comment]
I'm currently focusing on the next version, which, in theory, should not have this issue.

**Comment by MarketingPip** [comment]
@sebastianwessel - no worries. (Not that I am bugging you for this). Just figured maybe it might be help to you!

Cheers 🥂
